spring:
  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1522:xe
    username: cxl
    password: cxl
  jpa:
    hibernate:
      ddl-auto: update  #create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
  jackson:
    serialization:
      indent_output: true
  data:
     rest:
      base-path: /api
  profiles:
    active: dev

debug: true

settings:
  name: Git
  preName: CXL
